### ISSUE TITLE
exception during rule creation

### ISSUE THREAD

**Issue by andyvandesand** [TheAxelander/OpenBudgeteer#181]
When creating a new rule in the pre-release version, the following exception occurs:

warn: Microsoft.AspNetCore.Components.Server.Circuits.RemoteRenderer[100]
      Unhandled exception rendering component: Collection was modified; enumeration operation may not execute.
      System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
         at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
         at OpenBudgeteer.Blazor.Pages.Rules.BuildRenderTree(RenderTreeBuilder __builder) in /src/OpenBudgeteer.Blazor/Pages/Rules.razor:line 104
         at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment, Exception& renderFragmentException)
fail: Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost[111]
      Unhandled exception in circuit '4ZxZo6I_LGCq0AdocVWSqvugCwqZzg2VRQCp42PIDoI'.
      System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
         at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
         at OpenBudgeteer.Blazor.Pages.Rules.BuildRenderTree(RenderTreeBuilder __builder) in /src/OpenBudgeteer.Blazor/Pages/Rules.razor:line 104
         at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment, Exception& renderFragmentException)

**Comment by TheAxelander** [comment]
Duplicate, same issue as #165
