### ISSUE TITLE
Exception after canceling creation of a new Recurring Transactions

### ISSUE THREAD

**Issue by TheAxelander** [TheAxelander/OpenBudgeteer#210]
**Describe the bug**
An exception occurs after canceling creation of a new Recurring Transactions

**To Reproduce**
1. Go to Transaction Page
2. Click on 'Manage' of 'Add Recurring Transaction'
3. Click on 'Create Transaction'
4. Click on Cancel Button
5. See error

**Expected behavior**
No exception occurs

**Additional helpful details**
Exception according to Docker logs:
```
Unhandled exception rendering component: Object reference not set to an instance of an object.
      System.NullReferenceException: Object reference not set to an instance of an object.
         at OpenBudgeteer.Core.ViewModels.EntityViewModels.RecurringTransactionViewModel.CancelModification() in /src/OpenBudgeteer.Core/ViewModels/EntityViewModels/RecurringTransactionViewModel.cs:line 405
         at OpenBudgeteer.Blazor.Shared.RecurringTransactionDialog.<>c__DisplayClass0_0.<BuildRenderTree>b__9() in /src/OpenBudgeteer.Blazor/Shared/RecurringTransactionDialog.razor:line 79
         at Microsoft.AspNetCore.Components.EventCallbackWorkItem.InvokeAsync[T](MulticastDelegate delegate, T arg)
         at Microsoft.AspNetCore.Components.ComponentBase.Microsoft.AspNetCore.Components.IHandleEvent.HandleEventAsync(EventCallbackWorkItem callback, Object arg)
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.DispatchEventAsync(UInt64 eventHandlerId, EventFieldInfo fieldInfo, EventArgs eventArgs, Boolean waitForQuiescence)
fail: Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost[111]
      Unhandled exception in circuit 'DGURh76THEDcd18xOCJjjMG6YiggujOFzVJTaL7UB2I'.
      System.NullReferenceException: Object reference not set to an instance of an object.
         at OpenBudgeteer.Core.ViewModels.EntityViewModels.RecurringTransactionViewModel.CancelModification() in /src/OpenBudgeteer.Core/ViewModels/EntityViewModels/RecurringTransactionViewModel.cs:line 405
         at OpenBudgeteer.Blazor.Shared.RecurringTransactionDialog.<>c__DisplayClass0_0.<BuildRenderTree>b__9() in /src/OpenBudgeteer.Blazor/Shared/RecurringTransactionDialog.razor:line 79
         at Microsoft.AspNetCore.Components.EventCallbackWorkItem.InvokeAsync[T](MulticastDelegate delegate, T arg)
         at Microsoft.AspNetCore.Components.ComponentBase.Microsoft.AspNetCore.Components.IHandleEvent.HandleEventAsync(EventCallbackWorkItem callback, Object arg)
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.DispatchEventAsync(UInt64 eventHandlerId, EventFieldInfo fieldInfo, EventArgs eventArgs, Boolean waitForQuiescence)
```

**Comment by TheAxelander** [comment]
Confirmed existence in version `1.7.1`
