### ISSUE TITLE
Setting the webroot - trouble deploying behind traefik

### ISSUE THREAD

**Issue by nareto** [TheAxelander/OpenBudgeteer#86]
I'm trying to deploy this behind Traefik using docker swarm - I would like to have it at https://mydomain.com/ob. The Traefik configuration is done in the `docker-compose.yml` file:

```yml
    deploy:
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
        - "traefik.http.routers.openbudgeteer-https.rule=Host(`${DOMAIN}`) && PathPrefix(`/ob`)"
        - traefik.http.routers.openbudgeteer-https.entrypoints=https
        - traefik.http.routers.openbudgeteer-https.tls=true
        - traefik.http.services.openbudgeteer.loadbalancer.server.port=80
```

When I go to `https://${DOMAIN}/ob` I see this:
![image](https://user-images.githubusercontent.com/461518/156938604-a1b64cc3-82ec-4986-8a7f-54787c34ede1.png)

and when  I click on the links it ignores the `ob` prefix - for example clicking on Account goes to `https://${DOMAIN}/account`. The page actually displays correctly but this is not what I want...

So, is there anyway to explicitly tell openbudgeteer what it's root URL is?

These are the logs of the openbudgeteer container:

```
{"EventId":60,"LogLevel":"Warning","Category":"Microsoft.AspNetCore.DataProtection.Repositories.FileSystemXmlRepository","Message":"Storing keys in a directory \u0027/root/.aspnet/DataProtection-Keys\u0027 that may not be persisted outside of the container. Protected data will be unavailable when container is destroyed.","State":{"Message":"Storing keys in a directory \u0027/root/.aspnet/DataProtection-Keys\u0027 that may not be persisted outside of the container. Protected data will be unavailable when container is destroyed.","path":"/root/.aspnet/DataProtection-Keys","{OriginalFormat}":"Storing keys in a directory \u0027{path}\u0027 that may not be persisted outside of the container. Protected data will be unavailable when container is destroyed."}}
{"EventId":35,"LogLevel":"Warning","Category":"Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager","Message":"No XML encryptor configured. Key {6d62d128-4f93-4d36-8a05-df144bb49fd4} may be persisted to storage in unencrypted form.","State":{"Message":"No XML encryptor configured. Key {6d62d128-4f93-4d36-8a05-df144bb49fd4} may be persisted to storage in unencrypted form.","KeyId":"6d62d128-4f93-4d36-8a05-df144bb49fd4","{OriginalFormat}":"No XML encryptor configured. Key {KeyId:B} may be persisted to storage in unencrypted form."}}
{"EventId":14,"LogLevel":"Information","Category":"Microsoft.Hosting.Lifetime","Message":"Now listening on: http://[::]:80","State":{"Message":"Now listening on: http://[::]:80","address":"http://[::]:80","{OriginalFormat}":"Now listening on: {address}"}}
{"EventId":0,"LogLevel":"Information","Category":"Microsoft.Hosting.Lifetime","Message":"Application started. Press Ctrl\u002BC to shut down.","State":{"Message":"Application started. Press Ctrl\u002BC to shut down.","{OriginalFormat}":"Application started. Press Ctrl\u002BC to shut down."}}
{"EventId":0,"LogLevel":"Information","Category":"Microsoft.Hosting.Lifetime","Message":"Hosting environment: Production","State":{"Message":"Hosting environment: Production","envName":"Production","{OriginalFormat}":"Hosting environment: {envName}"}}
{"EventId":0,"LogLevel":"Information","Category":"Microsoft.Hosting.Lifetime","Message":"Content root path: /app","State":{"Message":"Content root path: /app","contentRoot":"/app","{OriginalFormat}":"Content root path: {contentRoot}"}}
{"EventId":3,"LogLevel":"Warning","Category":"Microsoft.AspNetCore.HttpsPolicy.HttpsRedirectionMiddleware","Message":"Failed to determine the https port for redirect.","State":{"Message":"Failed to determine the https port for redirect.","{OriginalFormat}":"Failed to determine the https port for redirect."}}
```

UPDATE: I'm not familiar with dotnet applications. I tried setting the root path setting the `ASPNETCORE_URLS` environment variable and also passing the url to the `--urls` option as suggested [here](https://andrewlock.net/5-ways-to-set-the-urls-for-an-aspnetcore-app/), but I get this exception (same in both cases):

```
ob_openbudgeteer.1.9tjlo69k716q@thor    | Unhandled exception. System.InvalidOperationException: A path base can only be configured using IApplicationBuilder.UsePathBase().
ob_openbudgeteer.1.9tjlo69k716q@thor    |    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.ParseAddress(String address, Boolean& https)
ob_openbudgeteer.1.9tjlo69k716q@thor    |    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.AddressesStrategy.BindAsync(AddressBindContext context, CancellationToken cancellationToken)
ob_openbudgeteer.1.9tjlo69k716q@thor    |    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindAsync(IEnumerable`1 listenOptions, AddressBindContext context, CancellationToken cancellationToken)
ob_openbudgeteer.1.9tjlo69k716q@thor    |    at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.BindAsync(CancellationToken cancellationToken)
ob_openbudgeteer.1.9tjlo69k716q@thor    |    at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.StartAsync[TContext](IHttpApplication`1 application, CancellationToken cancellationToken)
ob_openbudgeteer.1.9tjlo69k716q@thor    |    at Microsoft.AspNetCore.Hosting.GenericWebHostService.StartAsync(CancellationToken cancellationToken)
ob_openbudgeteer.1.9tjlo69k716q@thor    |    at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
ob_openbudgeteer.1.9tjlo69k716q@thor    |    at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
ob_openbudgeteer.1.9tjlo69k716q@thor    |    at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
ob_openbudgeteer.1.9tjlo69k716q@thor    |    at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
ob_openbudgeteer.1.9tjlo69k716q@thor    |    at OpenBudgeteer.Blazor.Program.Main(String[] args) in /src/OpenBudgeteer.Blazor/Program.cs:line 10
```

**Comment by TheAxelander** [comment]
I'm not sure if this can be easily set for Blazor Server apps, so I will most probably not be able to change this behavior. 
Why not using subdomains instead subdirectories?
